# This file was generated by GoReleaser. DO NOT EDIT.
cask "finfo" do
  name "finfo"
  desc "File info at a glance — metadata, checksums, binary analysis"
  homepage "https://github.com/oh-tarnished/finfo"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finfo"

  on_macos do
    on_intel do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "02233fb28c2d3856ffc43066468c6bc95330a3c0a0fb9a4973413a0cf1617313"
    end
    on_arm do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "45806cb0db245608aaaed81226ef9d703944d0e60badabfc7db798e35c2b9da1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "89405da7cb9245edc01cfcf283b6086101157b9696eb968d37bc706773cdbb95"
    end
    on_arm do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "41eab8f7de8d41fcede887ba0038624e2efef3fccab24481b85a14dfda432913"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finfo"]
    end
  end

  # No zap stanza required
end
