# This file was generated by GoReleaser. DO NOT EDIT.
cask "finfo" do
  name "finfo"
  desc "File info at a glance — metadata, checksums, binary analysis"
  homepage "https://github.com/oh-tarnished/finfo"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finfo"

  on_macos do
    on_intel do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "6bb56f9a8cf6f1c787f60278b2b0a61d0e6a77cd706020c86f122c480d44bbf9"
    end
    on_arm do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "2a76be38ee86b629eaabafc3aab46d99977d4a8826a6520b4cd5bc16418017c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "489e98c6c2195214cbecc6af934630934f3f575f8a78cd61a705e9c6f6ac2615"
    end
    on_arm do
      url "https://github.com/oh-tarnished/finfo/releases/download/v#{version}/finfo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/oh-tarnished/finfo/"
      sha256 "fd8859029c3d6008413746803eae4bc69be137f08c987a0f2b78cb50e505451b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finfo"]
    end
  end

  # No zap stanza required
end
