# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "3ef6dc7b2ed5258e9add16062b5b89cfad1100f97d7caca4ec75ac7a1d34a3e0"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "0bc9a391ba4bc5bcf13a539abba8bbab13cf03c693fa709de88f1b33bdfda01a"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "291293f5b5fa46bef07f543e2cbbd5e1baa122e4339a0841b4da12126e9a4ac5"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "964bfe88a661adb80b12c328d0e173930ae7294327de73a9a035a1d8c0a38aa4"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/oh-tarnished/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
