# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "830987bb9ef9544076bd967af8473247813c0149e1ba60f8188f40522dd6b20d"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "1a0c8b61382e3e35773cfbe328a90d5700891f0c320c4f5ac0816f9d4027223a"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "04fb58c1408dec3d31a668187b7097751f117da3c1677715caf5b9071c9d804a"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "214fbd442142a290b87fcb9a32346c1e89de77bba0f95356d47200b8f43e6a2c"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/oh-tarnished/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
