# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "2e21ac30e072afa45d6c009425601f4221654542548f7319d2f5591528bdeaaf"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "6092037801cece16f0cb462031e238a1b60fa42a3cd22278a4d2bfaf010ea5a5"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9d5aa88cfce4f65ca24742d681338a6ae1539188a7665c2dd2fae98b70c4bf9"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
    on_arm do
      sha256 "c556c5fd2497e61d92f0b946dd67a6c5116931e01e6200cb93094fc2faf96760"
      url "https://github.com/oh-tarnished/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/oh-tarnished/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/oh-tarnished/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
